
development:
   adapter: mysql2
   encoding: utf8
   reconnect: false
   database: paratodos_development
   username: root
   password: bela1010
   host: localhost

test:
   adapter: mysql2
   encoding: utf8
   reconnect: false
   database: paratodos_test
   username: root
   password: bela1010
   host: localhost

production:
   adapter: mysql2
   encoding: utf8
   reconnect: false
   database: paratodos_production
   username: root
   password: bela1010
   host: localhost
